install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 
  # install modules
  - npm install browserify -g
  - cd Consola
  - npm install
  - cd ..
  - nuget restore

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests

