install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 
  # install modules
  - npm install
  - npm install broswerify -g

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off