install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 
  # install modules
  - npm install browserify -g
  - nuget restore
  - cd Consola
  - npm install
  - cd ..

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests

build:
  project: Consola.sln

