install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 
  # install modules
  - npm install browserify -g
  - npm install exorcist -g
  - nuget restore
  - cd Consola
  - npm install
  - cd ..

configuration: 
  - Release
  - Debug

matrix:
  fast_finish: true

build:
  project: Consola.sln

test:
  assemblies:
    - '**\*.Tests.dll'